name: Test_CPLIIR_WeatherBench
model_type: SwinIRModel
scale: 1
num_gpu: 2
manual_seed: 42

datasets:
  
  val_1:
    name: Rain
    type: PairedImageDataset
    dataroot_gt: WeatherBench/rain/target
    dataroot_lq: WeatherBench/rain/input
    io_backend:
      type: disk

  val_2:
    name: Haze
    type: PairedImageDataset
    dataroot_gt: WeatherBench/haze/target
    dataroot_lq: WeatherBench/haze/input
    io_backend:
      type: disk

  val_3:
    name: Snow
    type: PairedImageDataset
    dataroot_gt: WeatherBench/snow/target
    dataroot_lq: WeatherBench/snow/input
    io_backend:
      type: disk


network_g:
  type: SparsePromptIR
  decoder: true

# path
path:
  pretrain_network_g: model_zoo/CPLIR_Weatherbench.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  use_grad_norm: 0.05
  ema_decay: 0.999
  ema_acc: 0.01
  tau: 10

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0.0
    betas: [0.9, 0.9]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000, 250000, 250000, 250000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 1000000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
